### ISSUE TITLE
Call to Sipi failed when trying to upload a .TIF

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Sipi#161]
Some images in .TIF from a research project cannot apparently be uploaded in Salsah by Sipi. I am not really confident regarding the data quality, formats, etc.

However, even though I got a "call to Sipi failed" error, I can open the file in Photoshop without problem. And when I save it as another file (the filename is not an issue), Sipi is then able to upload it.

Do you want me to provide you with those 2 images (34Mo each)?

**Comment by benjamingeer** [comment]
Yes please. You can put them on Dropbox or [SWITCHDrive](https://www.switch.ch/drive/) and post links to them here.

**Comment by lrosenth** [comment]
Hi Marion,


Please send a copy of a file that makes problems!

Greetings from Riga
Lukas

Von meinem iPhone gesendet

Am 18.05.2017 um 15:42 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


Yes please. You can put them on Dropbox or SWITCHDrive<https://www.switch.ch/drive/> and post links to them here.

**Comment by mrivoal** [comment]
https://drive.switch.ch/index.php/s/pCMA3oeCaECq9HB
https://drive.switch.ch/index.php/s/KBebqHgVEJ6iOIL

Thanks!

**Comment by mrivoal** [comment]
Currently, most of this project's images get the same "call to Sipi failed" error. If you could find some time to have a look at it, that would be nice :-)

**Comment by lrosenth** [comment]
I'm looking at it right this afternoon...
Lukas

Von meinem iPad gesendet

Am 01.06.2017 um 13:05 schrieb Marion Rivoal <notifications@github.com<mailto:notifications@github.com>>:


Currently, most of this project's images get the same "call to Sipi failed" error. If you could find some time to have a look at it, that would be nice :-)

**Comment by mrivoal** [comment]
I would love to have an update on this issue :-)

**Comment by mrivoal** [comment]
Back again. Does the current Sipi improvement #170 fix this issue? 
If not, I just want to let you know that it is quite pressing because we can't go productive with a project  unless this is fix. We can't either import their data because lots of their images have apparently the same problem.

**Comment by lrosenth** [comment]
Will look at it this afternoon! Sorry that it took so long....
Lukas

Von meinem iPad gesendet

Am 20.06.2017 um 10:54 schrieb Marion Rivoal <notifications@github.com<mailto:notifications@github.com>>:


Back again. Does the current Sipi improvement #170<https://github.com/dhlab-basel/Sipi/pull/170> fix this issue?
If not, I just want to let you know that it is quite pressing because we can't go productive with a project unless this is fix. We can't either import their data because lots of their images have apparently the same problem.

**Comment by benjamingeer** [comment]
@mrivoal Lukas tested this with #170, which I've just merged, and said it worked for him. Could you please test again now with the `develop` branch?

**Comment by mrivoal** [comment]
Yes, I will and let you know. Thanks.

**Comment by loicjaouen** [comment]
After updating our test platform, "it" still fails, see logs below.
Our test platform accesses sipi trough knora:
- is there more to do to make it compatible with Knora?
- do you want to split issues?

```
Sipi Version 1.0 Beta (build 2017-06-21 06:46)
Sipi Source Git-Version: a23cf93
Sipi: Sipi Version 1.0 Beta (build 2017-06-21 06:46)
Sipi: Sipi Source Git-Version: a23cf93
Sipi: Sipi server starting
Sipi: Serving images from /run/images
Sipi: Starting shttps server with 80 threads
Sipi: Added route /make_thumbnail with script ./scripts/make_thumbnail.lua
Sipi: Added route /convert_from_binaries with script ./scripts/convert_from_binaries.lua
Sipi: Added route /convert_from_file with script ./scripts/convert_from_file.lua
Sipi: Added route /Knora_login with script ./scripts/Knora_login.lua
Sipi: Added route /Knora_logout with script ./scripts/Knora_logout.lua
Sipi: Server listening on port 1024
Sipi: Accepted connection from 172.18.0.4
Sipi: Accepted connection from 172.18.0.4
Sipi: ScriptHandler: error executing lua script: Error at [/Sipi/shttps/LuaServer.cpp: 2699]: LuaServer::executeChunk failed: [string "--..."]:133: attempt to concatenate a boolean value (local 'result')
```

**Comment by lrosenth** [comment]
This seems to be a lua-script problem, not a intrinsic Sipi problem (that is not a file format conversion error, but something wrong witn the script doing the upload. I'll have a look at it with Tobias @tschweizer)

Sent from my iPad

On 21 Jun 2017, at 09:40, Loïc Jaouen <notifications@github.com<mailto:notifications@github.com>> wrote:


After updating our test platform, "it" still fails, see logs below.
Our test platform accesses sipi trough knora:

  *   is there more to do to make it compatible with Knora?
  *   do you want to split issues?

Sipi Version 1.0 Beta (build 2017-06-21 06:46)
Sipi Source Git-Version: a23cf93
Sipi: Sipi Version 1.0 Beta (build 2017-06-21 06:46)
Sipi: Sipi Source Git-Version: a23cf93
Sipi: Sipi server starting
Sipi: Serving images from /run/images
Sipi: Starting shttps server with 80 threads
Sipi: Added route /make_thumbnail with script ./scripts/make_thumbnail.lua
Sipi: Added route /convert_from_binaries with script ./scripts/convert_from_binaries.lua
Sipi: Added route /convert_from_file with script ./scripts/convert_from_file.lua
Sipi: Added route /Knora_login with script ./scripts/Knora_login.lua
Sipi: Added route /Knora_logout with script ./scripts/Knora_logout.lua
Sipi: Server listening on port 1024
Sipi: Accepted connection from 172.18.0.4
Sipi: Accepted connection from 172.18.0.4
Sipi: ScriptHandler: error executing lua script: Error at [/Sipi/shttps/LuaServer.cpp: 2699]: LuaServer::executeChunk failed: [string "--..."]:133: attempt to concatenate a boolean value (local 'result')

**Comment by subotic** [comment]
There is a fix on the way in PR #174.

**Comment by subotic** [comment]
@loicjaouen Just to let you know, as part of #174, I'm trying to get the `webapi` integration test working again. At some point in time, I started to get the same `ScriptHandler` error. After @lrosenth extended this error message to include the piece of lua code wich was causing the problem, the error stopped showing up. I will keep you posted.

**Comment by subotic** [comment]
@loicjaouen is there still a problem?

**Comment by loicjaouen** [comment]
@subotic : let me test right now; on which branch should I test?

**Comment by loicjaouen** [comment]
right, #174 has been merged, I grab `develop` and let you know in a short while.

**Comment by loicjaouen** [comment]
Yes, there is still a problem :(

```sh
Sipi Version 1.0 Beta (build 2017-06-30 12:50)
Sipi Source Git-Version: a82a370
Sipi: Sipi Version 1.0 Beta (build 2017-06-30 12:50)
Sipi: Sipi Source Git-Version: a82a370
Sipi: Sipi server starting
Sipi: Serving images from /run/images
Sipi: Starting shttps server with 80 threads
Sipi: Added route /make_thumbnail with script ./scripts/make_thumbnail.lua
Sipi: Added route /convert_from_binaries with script ./scripts/convert_from_binaries.lua
Sipi: Added route /convert_from_file with script ./scripts/convert_from_file.lua
Sipi: Added route /Knora_login with script ./scripts/Knora_login.lua
Sipi: Added route /Knora_logout with script ./scripts/Knora_logout.lua
Sipi: Server listening on port 1024
Sipi: Accepted connection from 172.18.0.4
Sipi: Accepted connection from 172.18.0.4
Sipi: Accepted connection from 172.18.0.4
Sipi: Accepted connection from 172.18.0.4
Sipi: Accepted connection from 172.18.0.4
Sipi: Nothing found in cache, reading and transforming file...
Sipi: Accepted connection from 172.18.0.4
Sipi: ScriptHandler: error executing lua script: Error at [/Sipi/shttps/LuaServer.cpp: 2736]: LuaServer::executeChunk failed: [string "--..."]:151: attempt to concatenate a boolean value (local 'result'), scriptname: ./scripts/make_thumbnail.lua
```

**Comment by subotic** [comment]
According to the error output, the `make_thumbnail.lua` at line 151 is causing the error.

This would be this bit of code:

```
local success, result = thumbImg:write(thumbsDir .. thumbName)
    if not success then
        send_error(500, "Couldn't create thumbnail: " .. result)
        return -1
    end
```

Basically, the send_error method has a bug. It fails to send back the error because `result` is not a string. You could try to wrap `result` in something like this: `tostring(result)`.

But why the writing of the thumbnail failed, I don't know. You could add this line before the send_error line, so see better what is happening:

```
server.log("thumbnail path: " .. thumbsDir .. thumbName)
```

and then check if there is maybe a file with the same name there or that the path exists.

**Comment by subotic** [comment]
These changes are also in PR #186 if you would like to try them out.

**Comment by loicjaouen** [comment]
thanks @subotic, here is the result:

```
Sipi Version 1.0 Beta (build 2017-07-03 10:59)
Sipi Source Git-Version: 6965722
Sipi: Sipi Version 1.0 Beta (build 2017-07-03 10:59)
Sipi: Sipi Source Git-Version: 6965722
Sipi: Sipi server starting
Sipi: Serving images from /run/images
Sipi: Starting shttps server with 80 threads
Sipi: Added route /make_thumbnail with script ./scripts/make_thumbnail.lua
Sipi: Added route /convert_from_binaries with script ./scripts/convert_from_binaries.lua
Sipi: Added route /convert_from_file with script ./scripts/convert_from_file.lua
Sipi: Added route /Knora_login with script ./scripts/Knora_login.lua
Sipi: Added route /Knora_logout with script ./scripts/Knora_logout.lua
Sipi: Server listening on port 1024
Sipi: Accepted connection from 172.18.0.4
Sipi: Accepted connection from 172.18.0.4
Sipi: Accepted connection from 172.18.0.4
Sipi: Accepted connection from 172.18.0.4
Sipi: Accepted connection from 172.18.0.4
Sipi: Accepted connection from 172.18.0.4
Sipi: Nothing found in cache, reading and transforming file...
Sipi: Accepted connection from 172.18.0.4
Sipi: ScriptHandler: error executing lua script: Error at [/Sipi/shttps/LuaServer.cpp: 2736]: LuaServer::executeChunk failed: [string "--..."]:151: attempt to concatenate a boolean value (local 'thumbName'), scriptname: ./scripts/make_thumbnail.lua
```

Apparently, all variables that are concatenated to the string should be stringified as you did for `result` (`tostring(result)`) on line:
```
local errorMsg = "Couldn't create thumbnail for path: " .. thumbsDir .. thumbName  .. ", result: " .. tostring(result)
```

**Comment by subotic** [comment]
strange. `thumbName` is already a string.

I have added a small change to the PR. now the thumbnail path should be printed out in the sipi log before the offending line. you need to set the level to `debug` in your sipi config, or you wan't see the debug output.

**Comment by subotic** [comment]
```
--
-- loglevel, one of "EMERGENCY", "ALERT", "CRITICAL", "ERROR", "WARNING", "NOTICE", "INFORMATIONAL", "DEBUG"
--
    loglevel = "DEBUG",

```

**Comment by loicjaouen** [comment]
```
Jul  4 09:13:09  Sipi[35206] <Info>: Accepted connection from 127.0.0.1
Jul  4 09:13:11  Sipi[35206] <Debug>: get_size: img_w=3492 img_h=2404 w=128 h=89 reduce=4 reduce only=0
Jul  4 09:13:12  Sipi[35206] <Debug>: thumbnail path: ./images/thumbs/IKbgm24XRP1-BniNwPfinyw.jpg
Jul  4 09:13:12  Sipi[35206] <Error>: ScriptHandler: error executing lua script: Error at [/Users/ljaouen/Soft/Code/github/Sipi/shttps/LuaServer.cpp: 2736]: LuaServer::executeChunk failed: [string "--..."]:154: attempt to concatenate a boolean value (local 'thumbPath'), scriptname: ./scripts/make_thumbnail.lua
```

at line:
```lua
local success, result = thumbImg:write(thumbPath)
```

`thumbPath` turns from srting to boolean... that sounds strange, testing in 604267079db24528204f303dcf9e9c4353210c4e :

```
Jul  4 09:38:47  Sipi[35423] <Debug>: thumbnail path: ./images/thumbs/Xieb5Rq7Xy-DnRm5iMAJAh.jpg
Jul  4 09:38:47  Sipi[35423] <Error>: ScriptHandler: error executing lua script: Error at [/Users/ljaouen/Soft/Code/github/Sipi/shttps/LuaServer.cpp: 2736]: LuaServer::executeChunk failed: [string "--..."]:153: attempt to concatenate a boolean value (local 'thumbPath'), scriptname: ./scripts/make_thumbnail.lua
```

testing hypothesis of variable changing type

**Comment by loicjaouen** [comment]
the file was written though:
```
ljaouen@SSP28034:~/Soft/Code/github/Sipi$ ls -lsa ./images/thumbs/Xieb5Rq7Xy-DnRm5iMAJAh.jpg
0 -rw-r--r--  1 ljaouen  staff     0B  4 jul 09:38 ./images/thumbs/Xieb5Rq7Xy-DnRm5iMAJAh.jpg
```

**Comment by loicjaouen** [comment]
here's another experiment then in 2b396530785ae0e04ab044532bb618937ef5ffd2 the result log is:

```
Jul  4 09:52:32  Sipi[35460] <Debug>: get_size: img_w=3492 img_h=2404 w=128 h=89 reduce=4 reduce only=0
Jul  4 09:52:33  Sipi[35460] <Debug>: thumbnail path: ./images/thumbs/HFbTHXaYjRF-D7lM4fN1Sbz.jpg
Jul  4 09:52:33  Sipi[35460] <Error>: Couldn't create thumbnail for path: false, result: false
```

I don't know lua or where the glue code to the C code is, but this looks more than very strange.

**Comment by subotic** [comment]
ok, maybe a problem with local vs. global variables.

**Comment by subotic** [comment]
I have made a small change.

Something else. Does `make check` run through?

**Comment by loicjaouen** [comment]
there is some progress:
```
Jul  4 11:29:42  Sipi[35898] <Debug>: get_size: img_w=3492 img_h=2404 w=128 h=89 reduce=4 reduce only=0
Jul  4 11:29:43  Sipi[35898] <Debug>: thumbnail path: ./images/thumbs/CPX8ssvBR5v-EYuar8cJG9X.jpg
Jul  4 11:29:43  Sipi[35898] <Error>: Couldn't create thumbnail for path: ./images/thumbs/CPX8ssvBR5v-EYuar8cJG9X.jpg, result: false
```

even though the file has been created.

**Comment by loicjaouen** [comment]
it's has been created but it is empty:
```
$ ls -lsa ./images/thumbs/CPX8ssvBR5v-EYuar8cJG9X.jpg
0 -rw-r--r--  1 ljaouen  staff     0B  4 jul 11:29 ./images/thumbs/CPX8ssvBR5v-EYuar8cJG9X.jpg
```

**Comment by subotic** [comment]
Ok, then there is still a problem with `sipi`. The method used to write the file is implemented in `sipi`. The file in question is which one of these?

- https://drive.switch.ch/index.php/s/FUa0Q9xbAN4FVDZ
- https://drive.switch.ch/index.php/s/eewqBm0NJZEHM8x

**Comment by loicjaouen** [comment]
both I think, but for the previous comments, I tried with the first link.

FYI: if you take the picture and remove the alpha channel (with preview), then it works.

**Comment by subotic** [comment]
@lrosenth could you please take a look. There is still a problem. I have added a test to #186. You only need to download  https://drive.switch.ch/index.php/s/FUa0Q9xbAN4FVDZ and put it in the `test/_test_data/images/knora` folder.

**Comment by subotic** [comment]
@loicjaouen I have added downloading of the FUa-etc. image to the test. This will allow running them on Travis, but also simplify running tests locally, as we don't need to download them by hand. I have taken the link from the switch drive, so please don't delete this image from the drive, or if you want to move it somewhere else, you can give me the new URL.

@lrosenth to test locally, simply change to the `wip/fix-scripts` branch and run `make check`.

**Comment by loicjaouen** [comment]
@subotic , do you want me to create and upload a version of [Leaves](https://github.com/dhlab-basel/Sipi/blob/develop/test/_test_data/images/knora/Leaves.jpg) that fails?

**Comment by subotic** [comment]
If it's going to be small in size, that would be great. I didn't want to add the large image to the repository, that's why I added the automated downloading.

**Comment by loicjaouen** [comment]
no problem, I'll add two versions of Leaves, reduced by 2/3rd, one with alpha layer and one without, that's 6Mo for both, I'll commit here.

**Comment by loicjaouen** [comment]
did so in: aa8cd776960c58ac813bf0c41f1d083a7228200b
left the download method, could be useful

**Comment by subotic** [comment]
thanks

**Comment by lrosenth** [comment]
I just tested SIPI with all the Leaves variant – not using the Knora-interface, but using the following
configuration in the "wip/fix-scripts" branch:
launch sipi: ```build/sipi --config config/sipi.config.lua```
open: ```http:// localhost:1024/server/upload.elua```in the browser
Upload the images. I tested the following images:
- DenyLeaves.jpg
- Leaves-small-alpha.tif
- Leaves-small-no-alpha.tif
- Leaves.jpg
- Leaves8.jpg
- Leaves8.tif
- RestrictLeaves.jpg
- ru12_bo_f_px_15_09_sas-r.tif
- ru09_sp_f_rn_12_06_kat-r.tif
I have no problems – all images are uploaded and converted just fine. Therefore I believe that the problem is not related to the C++ code but seems to be a problem problem related to the upload script used in the knora test...
I will try to figure out, but any help from @subotic, @loicjaouen is appreciated!

**Comment by subotic** [comment]
You are using a different script doing apparently different things ;-)

Here is a simpler test without lua involvement:

```
$ ./../../../build/sipi --format jpg -f Leaves-small-no-alpha.tif Leaves-small-no-alpha.jpg
$ ../../../../build/sipi --format jpg -f Leaves-small-alpha.tif Leaves-small-alpha.jpg
Sipi image error at [/Users/subotic/_github.com/sipi/src/SipiImage.cpp: 545]: Cannot remove component: nc=3 chan=2
```

**Comment by lrosenth** [comment]
Thanks – no I can reproduce it!

**Comment by lrosenth** [comment]
OK, the bug was only active when using the command line interface. Error fixed in the fix/fragmentarium branch.

**Comment by subotic** [comment]
ok, I will then move the tests to the `fragmentarium` branch.

**Comment by subotic** [comment]
wip is in PR #198
