### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Sipi#76]
# description

I know that it doesn't say much, yet:

`sipi` dies on a `Segmentation fault: 11` at the first request to upload a file.

```
$ ./build/sipi -config config/sipi.knora-config.lua

Sipi Version 1.0 Beta (build 2016-11-03 11:00)
Segmentation fault: 11
```

the log doesn't say more.

Let me know if I can provide more info.

# context

```
ljaouen@SSP28034:~/Soft/Code/github/Sipi$ git branch ; git log -1
  bugfixes
* develop
  master
  openssl
  wip/fix_Mac_compilation_error
commit 839b8f3e36187d6168906c3ea774d6248ac9a72b
Merge: eb84449 dfe9935
Author: Tobias Schweizer <tobiasschweizer@users.noreply.github.com>
Date:   Wed Oct 26 14:48:25 2016 +0200

    Merge pull request #73 from dhlab-basel/wip/knora-init

    fix (adapt sipi.init-knora-test.lua) add new error handling functions
```

Sipi freshly build.

running as my user with the `knora-config` file.

**Comment by benjamingeer** [comment]
Please attach the file you are trying to upload.

**Comment by loicjaouen** [comment]
![dsc_8249](https://cloud.githubusercontent.com/assets/3933654/19969452/e714ddd2-a1d8-11e6-9490-4276dc606dcd.JPG)

**Comment by loicjaouen** [comment]
here's the request:
```
POST /make_thumbnail HTTP/1.1
Host: localhost:1024
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0
Accept: */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://localhost:3335/index.html
Content-Length: 2495781
Content-Type: multipart/form-data; boundary=---------------------------40819492514693359571214972446
Origin: http://localhost:3335
Connection: keep-alive
```
the body looks fine on the sender's side, properly ending with the stated boundary.

**Comment by tobiasschweizer** [comment]
Are you sure that github did not convert the file when you uploaded it?

**Comment by loicjaouen** [comment]
Why, you manage to upload it?

There is no conversion: I saved the image back from github and compared (using `diff`) against the original; there is no difference.

**Comment by loicjaouen** [comment]
I didn't change the code, I only re-built, as previously, but I don't get the seg-fault anymore, the make_thumnail call is successfull and I see the thumbnail.
I later see another error in Knora, but that could be another error.

**Comment by loicjaouen** [comment]
one of the included 3rd party libs might have changed, distributing a binaries (monolithic executable, executable with libs, Docker image, etc) might help.

**Comment by loicjaouen** [comment]
here is another seg-fault, and I did build twice.

That's what pops-up in the console:
```
PNG with ICC profile: ./images/tmp/1LFNPJR575B-DxLZKQH5Lqb
terminate called after throwing an instance of 'Sipi::SipiImageError'
  what():  Num of components not 3 (nc = 4)!
/nas/scripts/knora/sipi : ligne 2 : 11260 Abandon                 (core dumped)./build/sipi -config config/sipi.knora-config.lua 2>&1 > /dev/null
```

log is empty.

<img width="1023" alt="capture d ecran 2016-10-24 a 11 03 26" src="https://cloud.githubusercontent.com/assets/3933654/20061038/51256ed0-a4fe-11e6-813d-53f148f96cd4.png">

**Comment by lrosenth** [comment]
OK, this has been a bug if a PNG or TIFF contained an alpha channel. The newest "develop"-branch should solve it (tested with above image...)

**Comment by loicjaouen** [comment]
great; those two pictures work fine now.

This one still produces a seg-fault though:

![dsc_0079](https://cloud.githubusercontent.com/assets/3933654/20106264/d5a0d5d8-a5d4-11e6-8baf-d9f3d19aad22.JPG)

**Comment by benjamingeer** [comment]
@loicjaouen Can you still reproduce this bug, or can I close this issue?

**Comment by loicjaouen** [comment]
JPG works fine now.
Otherwise, I can't say for sure as I can't upload PNG.

**Comment by benjamingeer** [comment]
OK thanks.
